version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: messly_user
      POSTGRES_PASSWORD: messly
      POSTGRES_DB: messlydb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - messly_net

  website:
    build:
      context: ./website
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - messly_net
    environment:
      DATABASE_URL: "postgresql://messly_user:messly@db:5432/messlydb"
    volumes:
      - ./website/app/static:/app/static

  chat:
    build:
      context: ./chat
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - messly_net
    environment:
      DATABASE_URL: "postgresql://messly_user:messly@db:5432/messlydb"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - messly_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website
      - chat
      - frontend
    networks:
      - messly_net

networks:
  messly_net:
    driver: bridge

volumes:
  db_data:
